### ISSUE TITLE
教材66页il8n问题

### ISSUE THREAD

**Issue by blackdust** [blackdust/depot1#4]
一模一样输入的可是。。。
<img src='http://img.teamkn.com/i/f5GJnDkH.png' />
网上查了下有类似的问题 可惜看不懂

**Comment by blackdust** [comment]
<img src='http://img.teamkn.com/i/vERVXqgN.png' />

**Comment by ben7th** [comment]
第一个截图上的错误是因为找不到 i18n 配置文件中对应的内容

目前工程采用的是默认设置，所以 i18n 配置文件位于 `config/locales/en.yml`

错误提示的意思是，尝试查找 en.activerecord.errors.messages.taken 但是没有找到
所以显示成了 translation missing ....

解决的方法是，在 i18n 配置文件，也就是  en.yml 中添加：

``` yaml
en:
  activerecord:
    errors:
      messages:
        taken: has already been taken
```

意思是，当试图通过 i18n.translate 函数去调用 'en.activerecord.errors.messages.taken' 参数时
会在 en.yml 里找到上述位置，并取得对应的字符串，也就是 'has already been taken' 并返回

这样就可以匹配测试了
